-- MySQL Script generated by MySQL Workbench
-- Fri Jan 18 15:10:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

USE `eventscalender` ;

-- -----------------------------------------------------
-- Table `eventscalender`.`organizer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventscalender`.`organizer` (
  `idorganizer` INT NOT NULL AUTO_INCREMENT,
  `organizer` VARCHAR(45) NULL,
  PRIMARY KEY (`idorganizer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventscalender`.`crawler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventscalender`.`crawler` (
  `idcrawler` INT NOT NULL AUTO_INCREMENT,
  `url_crawler` VARCHAR(5000) NULL,
  PRIMARY KEY (`idcrawler`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventscalender`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventscalender`.`event` (
  `idevent` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `description` LONGTEXT NULL,
  `link` VARCHAR(5000) NOT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `idgroup` INT NULL,
  `advance_price` DOUBLE NULL,
  `sale_price` DOUBLE NULL,
  `event_site` VARCHAR(200) NULL,
  `idorganizer` INT NULL,
  `image_url` VARCHAR(5000) NULL,
  `category` VARCHAR(45) NULL,
  `time_start` TIME NULL,
  `time_end` TIME NULL,
  `idcrawler` INT NULL,
  `street` VARCHAR(200) NULL,
  `city` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `lng` DOUBLE NULL,
  `lat` DOUBLE NULL,
  `booking_office` VARCHAR(200) NULL,
  PRIMARY KEY (`idevent`),
  INDEX `idorganizer_idx` (`idorganizer` ASC),
  INDEX `idcrawler_idx` (`idcrawler` ASC),
  CONSTRAINT `idorganizer`
    FOREIGN KEY (`idorganizer`)
    REFERENCES `eventscalender`.`organizer` (`idorganizer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idcrawler`
    FOREIGN KEY (`idcrawler`)
    REFERENCES `eventscalender`.`crawler` (`idcrawler`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


#SET SQL_MODE=@OLD_SQL_MODE;
#SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
#SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
